### POST REQUEST
POST http://localhost:3000/api/jsonBlob
Content-Type: application/json

{
    "test": "test"
}

### GET REQUEST
GET http://localhost:3000/api/jsonBlob/64506a5baec02d96f1defed3

### PUT REQUEST
PUT http://localhost:3000/api/jsonBlob/6445e798242363962cba365c
Content-Type: application/json

{
    "test": 10
}

### DELETE REQUEST
DELETE http://localhost:3000/api/jsonBlob/64506a5baec02d96f1defed3

### SIGN UP
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "cody.king04@outlook.com",
    "password": "password123"
}

### SIGN IN
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "cody.king04@outlook.com",
    "password": "password123"
}